version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: springsnake
      MONGO_INITDB_ROOT_PASSWORD: waQxTVZ48hPBFc4
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
        read_only: false
networks:
    default:
        name: springsnake_network
volumes:
    dbdata: