version: 3
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: springsnake
      MONGO_INITDB_ROOT_PASSWORD: waQxTVZ48hPBFc4
    volumes:
      - ./dbdata:/data/db
  mongo-espress:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: springsnake
      ME_CONFIG_MONGODB_ADMINPASSWORD: waQxTVZ48hPBFc4
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
networks:
    default:
        name: springsnake_network